[settings]
experimental = true

[tools]
actionlint = "1.7.11"
cocogitto = "6.5.0"
"github:miniscruff/changie" = "1.25.0"
git-cliff = "2.12.0"
markdownlint-cli2 = "0.22.0"
node = "22.22.1"
"npm:oxfmt" = "0.41.0"
"npm:oxlint" = "1.56.0"
uv = "0.11.26"
"pipx:mdformat" = { version = "1.0.0", uvx_args = "--with-requirements mdformat-requirements.lock" }
yamllint = "1.38.0"
