name: 'OpenTofu Validate'
description: 'Validate OpenTofu configuration'
inputs:
  working-directory:
    description: 'Directory containing OpenTofu configuration'
    required: false
    default: 'tofu'
runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
      run: node -e "require('${{ github.action_path }}/dist/index.js')()"
