// Generates the conftest configuration file the pinned evaluation runs with.
//
// Conftest loads conftest.{toml,yaml,json,...} from its working directory.
// That directory is the consumer checkout, and keys there steer the evaluation.
// An `update` key downloads over the verified policy directory before it loads.
// A `parser` key reduces the plan to nothing and `no-fail` hides violations.
// Passing this generated file to --config-file shadows every consumer file.

const { writeFileSync } = require("node:fs");
const { join } = require("node:path");

const ISOLATED_CONFIG_FILE = "conftest-pinned.toml";

const ISOLATED_CONFIG_CONTENT = `# Generated by pretty-good-software-org/ci-shared actions/tofu/policy.
# Intentionally empty: it shadows any conftest configuration file in the consumer
# checkout so only this action's flags decide what conftest evaluates.
`;

// The isolated file lives beside the checked-out policy, never inside it.
// Keeping it out of the policy directory keeps it out of the tree digest.
const writeIsolatedConfig = (checkoutRoot: string): string => {
  const configFile = join(checkoutRoot, ISOLATED_CONFIG_FILE);
  writeFileSync(configFile, ISOLATED_CONFIG_CONTENT, "utf8");
  return configFile;
};

module.exports = { ISOLATED_CONFIG_FILE, writeIsolatedConfig };
