#!/usr/bin/env bash
#MISE description="Run all linters"
#MISE depends=["check:markdown-format", "lint:actions", "lint:yaml", "lint:markdown", "lint:ts", "lint:typecheck", "lint:format:check"]
set -euo pipefail
